### ISSUE TITLE
[Documentation] "Metric" in the Community Handbook

### ISSUE THREAD

**Issue by jaskiratsingh2000** [jaskiratsingh2000/Google-Season-of-Docs#37]
While I was applying to the GSoD under CHAOSS back in the month of May, I had made a fair research around the metric system on the CHAOSS community. I was always curious to know that how one can propose the metric and follow the path for its approval.
Taking that into consideration, I planned to write the "**Processes for getting approved to be visible on the website**" along with the "**CHAOSS Metric Committee**", and "**Useful Resources**"

**Comment by jaskiratsingh2000** [comment]
Here is the link to view the Metric page within the handbook - https://handbook.chaoss.community/community-handbook/metrics

**Comment by foundjem** [comment]
Hi Jaskirat,
great! Keep it simple and to the point.

Regards,
Armstrong

**Comment by jaskiratsingh2000** [comment]
Thanks @foundjem !

I really appreciate your feedback.
